#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

sudo /etc/init.d/tomcat7 stop
./gradlew clean war
sudo rm -r /usr/share/tomcat7/webapps/fineract-provider
sudo rm /usr/share/tomcat7/webapps/fineract-provider.war
sudo mv build/libs/fineract-provider.war /usr/share/tomcat7/webapps
sudo /etc/init.d/tomcat7 start
